### ISSUE TITLE
Attribution error while predicting chromatin profiles with fasta file

### ISSUE THREAD

**Issue by pyareedash** [FunctionLab/sei-framework#18]
Hi,
While trying to run the following command I can't get past this error, my hunch is it's from selene-sdk (newest version 0.5.0)

`sh 1_sequence_prediction.sh <input-file> <genome> <output-dir> --cuda`

And I get,

`use_cuda: True
Traceback (most recent call last):
  File "1_sequence_prediction.py", line 73, in <module>
    parse_configs_and_run(configs)
  ...
    if not self.reference_sequence._initialized:
AttributeError: type object 'Genome' has no attribute '_initialized'`

Thank you in advance!

**Comment by kathyxchen** [comment]
Hi, thanks for your message. How did you install selene? If you can share your exact command that would also help. Happy to discuss here or via email chen.kathleenm@gmail.com if that's easier.

**Comment by pyareedash** [comment]
Hi,
Thank you for your response!
I tried installing with conda/mamba for e.g., `mamba install -c bioconda selene-sdk` and `mamba install selene-sdk=0.5`. 
Shall I try installing it from the GitHub repo maybe?

**Comment by pyareedash** [comment]
Update: I tried `pip install selene-sdk==0.5.1` and seems to work (running with no errors). 

I will update more once it completes the run :)

**Comment by kathyxchen** [comment]
Noted thanks for the update and keep me posted! I'll make a note to check if we need to be more clear on versioning, conda installation details, etc

**Comment by pyareedash** [comment]
Yes, working with `selene-sdk==0.5.1` (via pip installation)  
Thank you very much!
